# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c3cc6b9d2c2972803831e57225477431"
name = "Bundle Studio"
application_url = "https://frog-cardiff-woods-marriage.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/products"
  topics = [ "products/update", "products/delete" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders"
  topics = [ "orders/cancelled", "orders/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/inventory"
  topics = [ "inventory_levels/update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_orders,read_products,write_discounts,write_products"

[auth]
redirect_urls = [
  "https://frog-cardiff-woods-marriage.trycloudflare.com/auth/callback"
]

[app_proxy]
url = "https://frog-cardiff-woods-marriage.trycloudflare.com/proxy"
subpath = "flights"
prefix = "apps"
